# TUGAS 1 DATA MINING

### DIAN VITIANA NINGRUM (06211540000020)

In [1]:
## IMPORT PACKAGES
import pandas as pd
import numpy as np

In [6]:
#load data
data1 = pd.read_csv (r'E:/datatugas11.csv')
data2 =pd.read_csv(r'E:/datatugas12.csv')

In [7]:
data1.head()

,NRP,JURUSAN,JUMLAH GRUP LINE,JUMLAH GRUP WHATSAPP,LAMA WAKTU BERMAIN;;;;;
1213100096,MATEMATIKA,4,12,2,15;;;;;
1213100083,MATEMATIKA,5,6,1,6;;;;;
1314100084,S1-STATISTIKA,5,60,0,0.5;;;;;
1314030087,D3-STATISTIKA,6,35,8,1;;;;;
3312100082,S1-TEKNIK LINGKUNGAN,7,25,2,4;;;;;

In [8]:
data1.tail()

,NRP,JURUSAN,JUMLAH GRUP LINE,JUMLAH GRUP WHATSAPP,LAMA WAKTU BERMAIN;;;;;
2213100121,S1-TEKNIK ELEKTRO,4,25,0,2;;;;;
1112100016,FISIKA,6,15,17,2;;;;;
1314030006,D3-STATISTIKA,4,18,0,3;;;;;
1313030014,D3-SATISTIKA,4,20,3,4;;;;;
2914100045,TEKNIK MULTIMEDIA JARINGAN,3,15,0,5;;;;;

In [9]:
data2.head()

,NRP,JUMLAH SKS,JUMLAH ORGANISASI,LAMA BELAJAR,LAMA TIDUR,IPK;;;;;
0,1213100096,97,2,1.0,8,2.99;;;;;
1,1213100083,99,2,1.0,8,3.28;;;;;
2,1314100084,56,2,2.0,5,3.46;;;;;
3,1314030087,56,3,4.0,5,3.82;;;;;
4,3312100082,117,1,3.0,7,3.26;;;;;

In [10]:
data2.tail()

,NRP,JUMLAH SKS,JUMLAH ORGANISASI,LAMA BELAJAR,LAMA TIDUR,IPK;;;;;
104,2213100121,96,2,1.0,4,2.47;;;;;
105,1112100016,123,4,2.0,4,2.78;;;;;
106,1314030006,43,1,2.0,5,2.02;;;;;
107,1313030014,101,2,2.0,3,3.51;;;;;
108,2914100045,60,3,4.0,5,3.45;;;;;

In [23]:
# merge data based on ID
data = pd.concat([data2, data1])
data

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,IPK;;;;;,JUMLAH GRUP WHATSAPP,JURUSAN,JUMLAH GRUP LINE,JUMLAH ORGANISASI,JUMLAH SKS,LAMA BELAJAR,LAMA TIDUR,LAMA WAKTU BERMAIN;;;;;,NRP
0,2.99;;;;;,NaN,NaN,NaN,2.0,97.0,1.0,8,NaN,1213100096
1,3.28;;;;;,NaN,NaN,NaN,2.0,99.0,1.0,8,NaN,1213100083
2,3.46;;;;;,NaN,NaN,NaN,2.0,56.0,2.0,5,NaN,1314100084
3,3.82;;;;;,NaN,NaN,NaN,3.0,56.0,4.0,5,NaN,1314030087
4,3.26;;;;;,NaN,NaN,NaN,1.0,117.0,3.0,7,NaN,3312100082
5,3.55;;;;;,NaN,NaN,NaN,2.0,70.0,3.0,7,NaN,2313030075
6,3.28;;;;;,NaN,NaN,NaN,1.0,58.0,2.0,6,NaN,4214101018
7,3.64;;;;;,NaN,NaN,NaN,1.0,139.0,2.0,6,NaN,4212101006
8,3.14;;;;;,NaN,NaN,NaN,4.0,70.0,3.0,4,NaN,2313030043
9,2.9;;;;;,NaN,NaN,NaN,8.0,58.0,3.0,5,NaN,2414100111
10,3.4;;;;;,NaN,NaN,NaN,1.0,144.0,2.0,5,NaN,2812100110
11,3.01;;;;;,NaN,NaN,NaN,4.0,56.0,2.0,4,NaN,3514100062
12,3.3;;;;;,NaN,NaN,NaN,0.0,100.0,3.0,6,NaN,3213100031
13,3;;;;;,NaN,NaN,NaN,0.0,105.0,3.0,6,NaN,3213100037
14,2.78;;;;;,NaN,NaN,NaN,2.0,120.0,1.0,5,NaN,2412100071
15,2.4;;;;;,NaN,NaN,NaN,3.0,56.0,4.0,4,NaN,2114030040
16,3.53;;;;;,NaN,NaN,NaN,2.0,60.0,6.0,5,NaN,3614100016
17,3.28;;;;;,NaN,NaN,NaN,3.0,138.0,7.0,8,NaN,3612100006
18,3.48;;;;;,NaN,NaN,NaN,3.0,58.0,3.0,6,NaN,3614100015
19,3.1;;;;;,NaN,NaN,NaN,1.0,138.0,3.0,8,NaN,3612100019
20,3.56;;;;;,NaN,NaN,NaN,4.0,104.0,2.0,7,NaN,3613100009
21,3.26;;;;;,NaN,NaN,NaN,1.0,109.0,4.0,5,NaN,3713100011
22,3;;;;;,NaN,NaN,NaN,2.0,135.0,1.0,5,NaN,3512100079
23,3.3;;;;;,NaN,NaN,NaN,1.0,135.0,1.0,5,NaN,3512100042
24,2.93;;;;;,NaN,NaN,NaN,2.0,131.0,3.0,4,NaN,2112100031
25,3.07;;;;;,NaN,NaN,NaN,2.0,127.0,1.0,5,NaN,2112100033
26,3.4;;;;;,NaN,NaN,NaN,2.0,55.0,2.0,5,NaN,2114100150
27,2.36;;;;;,NaN,NaN,NaN,2.0,86.0,2.0,5,NaN,1112100053
28,3.09;;;;;,NaN,NaN,NaN,1.0,39.0,10.0,4,NaN,1114100107
29,2.94;;;;;,NaN,NaN,NaN,1.0,93.0,3.0,6,NaN,1313100077
...,...,...,...,...,...,...,...,...,...,...
2112030009,NaN,3,6.0,4.0,NaN,NaN,NaN,NaN,3;;;;;,D3-TEKNIK MESIN
4413100012,NaN,1,5.0,10.0,NaN,NaN,NaN,NaN,5;;;;;,SISTEM TRANSPORTASI LAUT
2413100038,NaN,2,2.0,38.0,NaN,NaN,NaN,NaN,0;;;;;,TEKNIK FISIKA
2214030051,NaN,0,2.0,14.0,NaN,NaN,NaN,NaN,2;;;;;,D3-TEKNIK ELEKTRO
1114100063,NaN,10,4.0,39.0,NaN,NaN,NaN,NaN,1;;;;;,FISIKA
2713100027,NaN,5,5.0,20.0,NaN,NaN,NaN,NaN,2;;;;;,TEKNIK MATERIAL
4213100032,NaN,2,3.0,9.0,NaN,NaN,NaN,NaN,2;;;;;,SISTEM PERKAPALAN
4213100017,NaN,2,4.0,81.0,NaN,NaN,NaN,NaN,5;;;;;,SISTEM PERKAPALAN
4214100009,NaN,4,7.0,52.0,NaN,NaN,NaN,NaN,2;;;;;,SISTEM PERKAPALAN
4214100093,NaN,0,5.0,30.0,NaN,NaN,NaN,NaN,2;;;;;,SISTEM PERKPALAN
2414100078,NaN,7,7.0,50.0,NaN,NaN,NaN,NaN,3;;;;;,TEKNIK FISIKA
2314100004,NaN,0,3.0,3.0,NaN,NaN,NaN,NaN,3;;;;;,S1-TENIK FISIKA
4113100058,NaN,1,4.0,42.0,NaN,NaN,NaN,NaN,0;;;;;,TEKNIK PERKAPALAN
4113100039,NaN,0,2.0,24.0,NaN,NaN,NaN,NaN,3;;;;;,TEKNIK PERKAPALAN
1413100010,NaN,5,4.0,15.0,NaN,NaN,NaN,NaN,2;;;;;,KIMIA
1414100107,NaN,4,4.0,56.0,NaN,NaN,NaN,NaN,3;;;;;,KIMIA
1413100077,NaN,0,4.0,15.0,NaN,NaN,NaN,NaN,2;;;;;,KIMIA
1414100019,NaN,10,3.0,25.0,NaN,NaN,NaN,NaN,1;;;;;,KIMIA
2113100072,NaN,0,4.0,30.0,NaN,NaN,NaN,NaN,3;;;;;,S1-TEKNIK MESIN
2113100079,NaN,3,3.0,29.0,NaN,NaN,NaN,NaN,2;;;;;,S1-TEKNIK MESIN
2213100134,NaN,4,3.0,32.0,NaN,NaN,NaN,NaN,2;;;;;,S1-TEKNIK ELEKTRO
2212100042,NaN,2,5.0,13.0,NaN,NaN,NaN,NaN,4;;;;;,S1-TEKNIK ELEKTRO
2212100182,NaN,10,5.0,22.0,NaN,NaN,NaN,NaN,2;;;;;,S1-TEKNIK ELEKTRO
2214100121,NaN,1,4.0,55.0,NaN,NaN,NaN,NaN,3;;;;;,S1-TEKNIK ELEKTRO
2214100004,NaN,1,6.0,35.0,NaN,NaN,NaN,NaN,4;;;;;,S1-TEKNIK ELEKTRO
2213100121,NaN,0,4.0,25.0,NaN,NaN,NaN,NaN,2;;;;;,S1-TEKNIK ELEKTRO
1112100016,NaN,17,6.0,15.0,NaN,NaN,NaN,NaN,2;;;;;,FISIKA
1314030006,NaN,0,4.0,18.0,NaN,NaN,NaN,NaN,3;;;;;,D3-STATISTIKA
1313030014,NaN,3,4.0,20.0,NaN,NaN,NaN,NaN,4;;;;;,D3-SATISTIKA
2914100045,NaN,0,3.0,15.0,NaN,NaN,NaN,NaN,5;;;;;,TEKNIK MULTIMEDIA JARINGAN

In [24]:
# unsert new colomn
data['JUMLAH GROUP SOSMED'] = data1[' JUMLAH GRUP WHATSAPP']+ data1['JUMLAH GRUP LINE']
data

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

In [25]:
# delete colomn
data3 = data.drop(['JUMLAH SKS'], axis=1)
data3

,IPK;;;;;,JUMLAH GRUP WHATSAPP,JURUSAN,JUMLAH GRUP LINE,JUMLAH ORGANISASI,LAMA BELAJAR,LAMA TIDUR,LAMA WAKTU BERMAIN;;;;;,NRP
0,2.99;;;;;,NaN,NaN,NaN,2.0,1.0,8,NaN,1213100096
1,3.28;;;;;,NaN,NaN,NaN,2.0,1.0,8,NaN,1213100083
2,3.46;;;;;,NaN,NaN,NaN,2.0,2.0,5,NaN,1314100084
3,3.82;;;;;,NaN,NaN,NaN,3.0,4.0,5,NaN,1314030087
4,3.26;;;;;,NaN,NaN,NaN,1.0,3.0,7,NaN,3312100082
5,3.55;;;;;,NaN,NaN,NaN,2.0,3.0,7,NaN,2313030075
6,3.28;;;;;,NaN,NaN,NaN,1.0,2.0,6,NaN,4214101018
7,3.64;;;;;,NaN,NaN,NaN,1.0,2.0,6,NaN,4212101006
8,3.14;;;;;,NaN,NaN,NaN,4.0,3.0,4,NaN,2313030043
9,2.9;;;;;,NaN,NaN,NaN,8.0,3.0,5,NaN,2414100111
10,3.4;;;;;,NaN,NaN,NaN,1.0,2.0,5,NaN,2812100110
11,3.01;;;;;,NaN,NaN,NaN,4.0,2.0,4,NaN,3514100062
12,3.3;;;;;,NaN,NaN,NaN,0.0,3.0,6,NaN,3213100031
13,3;;;;;,NaN,NaN,NaN,0.0,3.0,6,NaN,3213100037
14,2.78;;;;;,NaN,NaN,NaN,2.0,1.0,5,NaN,2412100071
15,2.4;;;;;,NaN,NaN,NaN,3.0,4.0,4,NaN,2114030040
16,3.53;;;;;,NaN,NaN,NaN,2.0,6.0,5,NaN,3614100016
17,3.28;;;;;,NaN,NaN,NaN,3.0,7.0,8,NaN,3612100006
18,3.48;;;;;,NaN,NaN,NaN,3.0,3.0,6,NaN,3614100015
19,3.1;;;;;,NaN,NaN,NaN,1.0,3.0,8,NaN,3612100019
20,3.56;;;;;,NaN,NaN,NaN,4.0,2.0,7,NaN,3613100009
21,3.26;;;;;,NaN,NaN,NaN,1.0,4.0,5,NaN,3713100011
22,3;;;;;,NaN,NaN,NaN,2.0,1.0,5,NaN,3512100079
23,3.3;;;;;,NaN,NaN,NaN,1.0,1.0,5,NaN,3512100042
24,2.93;;;;;,NaN,NaN,NaN,2.0,3.0,4,NaN,2112100031
25,3.07;;;;;,NaN,NaN,NaN,2.0,1.0,5,NaN,2112100033
26,3.4;;;;;,NaN,NaN,NaN,2.0,2.0,5,NaN,2114100150
27,2.36;;;;;,NaN,NaN,NaN,2.0,2.0,5,NaN,1112100053
28,3.09;;;;;,NaN,NaN,NaN,1.0,10.0,4,NaN,1114100107
29,2.94;;;;;,NaN,NaN,NaN,1.0,3.0,6,NaN,1313100077
...,...,...,...,...,...,...,...,...,...
2112030009,NaN,3,6.0,4.0,NaN,NaN,NaN,3;;;;;,D3-TEKNIK MESIN
4413100012,NaN,1,5.0,10.0,NaN,NaN,NaN,5;;;;;,SISTEM TRANSPORTASI LAUT
2413100038,NaN,2,2.0,38.0,NaN,NaN,NaN,0;;;;;,TEKNIK FISIKA
2214030051,NaN,0,2.0,14.0,NaN,NaN,NaN,2;;;;;,D3-TEKNIK ELEKTRO
1114100063,NaN,10,4.0,39.0,NaN,NaN,NaN,1;;;;;,FISIKA
2713100027,NaN,5,5.0,20.0,NaN,NaN,NaN,2;;;;;,TEKNIK MATERIAL
4213100032,NaN,2,3.0,9.0,NaN,NaN,NaN,2;;;;;,SISTEM PERKAPALAN
4213100017,NaN,2,4.0,81.0,NaN,NaN,NaN,5;;;;;,SISTEM PERKAPALAN
4214100009,NaN,4,7.0,52.0,NaN,NaN,NaN,2;;;;;,SISTEM PERKAPALAN
4214100093,NaN,0,5.0,30.0,NaN,NaN,NaN,2;;;;;,SISTEM PERKPALAN
2414100078,NaN,7,7.0,50.0,NaN,NaN,NaN,3;;;;;,TEKNIK FISIKA
2314100004,NaN,0,3.0,3.0,NaN,NaN,NaN,3;;;;;,S1-TENIK FISIKA
4113100058,NaN,1,4.0,42.0,NaN,NaN,NaN,0;;;;;,TEKNIK PERKAPALAN
4113100039,NaN,0,2.0,24.0,NaN,NaN,NaN,3;;;;;,TEKNIK PERKAPALAN
1413100010,NaN,5,4.0,15.0,NaN,NaN,NaN,2;;;;;,KIMIA
1414100107,NaN,4,4.0,56.0,NaN,NaN,NaN,3;;;;;,KIMIA
1413100077,NaN,0,4.0,15.0,NaN,NaN,NaN,2;;;;;,KIMIA
1414100019,NaN,10,3.0,25.0,NaN,NaN,NaN,1;;;;;,KIMIA
2113100072,NaN,0,4.0,30.0,NaN,NaN,NaN,3;;;;;,S1-TEKNIK MESIN
2113100079,NaN,3,3.0,29.0,NaN,NaN,NaN,2;;;;;,S1-TEKNIK MESIN
2213100134,NaN,4,3.0,32.0,NaN,NaN,NaN,2;;;;;,S1-TEKNIK ELEKTRO
2212100042,NaN,2,5.0,13.0,NaN,NaN,NaN,4;;;;;,S1-TEKNIK ELEKTRO
2212100182,NaN,10,5.0,22.0,NaN,NaN,NaN,2;;;;;,S1-TEKNIK ELEKTRO
2214100121,NaN,1,4.0,55.0,NaN,NaN,NaN,3;;;;;,S1-TEKNIK ELEKTRO
2214100004,NaN,1,6.0,35.0,NaN,NaN,NaN,4;;;;;,S1-TEKNIK ELEKTRO
2213100121,NaN,0,4.0,25.0,NaN,NaN,NaN,2;;;;;,S1-TEKNIK ELEKTRO
1112100016,NaN,17,6.0,15.0,NaN,NaN,NaN,2;;;;;,FISIKA
1314030006,NaN,0,4.0,18.0,NaN,NaN,NaN,3;;;;;,D3-STATISTIKA
1313030014,NaN,3,4.0,20.0,NaN,NaN,NaN,4;;;;;,D3-SATISTIKA
2914100045,NaN,0,3.0,15.0,NaN,NaN,NaN,5;;;;;,TEKNIK MULTIMEDIA JARINGAN